# Package for PyPI

name: 'packaging'

on: 
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version: ['3.7']

    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@v3

    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: 'Install packaging software'
      run: pip install --upgrade setuptools build twine

    - name: 'Print package versions'
      run: pip list

    - name: 'Package code using build'
      run: python -m build

    - name: 'Check package using twine'
      run: python -m twine check dist/*

    - name: 'Extract branch name'
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
      id: extract_branch

    - name: 'Install from github branch and run a test'
      run: |
        pip install pytest git+https://github.com/broadinstitute/CellBender@${{ steps.extract_branch.outputs.branch }}
        cellbender -v
